name: 02 - Workflow events
on: 
  push:
  pull_request:
  schedule: 
    - cron: '*/5 * * * *' # Every 5 minutes is the lowest
  workflow_dispatch:
    
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "Triggered by a(n) ${{github.event_name}}"
